fiz:
	cp fizzbuzz.js prg.js

test:
	cat uno.txt | node prg.js 
	cat dos.txt | node prg.js 
	cat tres.txt | node prg.js 
	cat cuatro.txt | node prg.js 
	cat cinco.txt | node prg.js 
	cat seis.txt | node prg.js 
